// Emoji 数据集：覆盖基础、变体选择符、肤色、ZWJ 序列、旗帜五大类。
// keywords 同时包含中英文，供搜索使用。

export const EMOJI_DATA = [
  // ---- 基础 ----
  { id: 'grinning', emoji: '😀', name: '露齿笑脸', nameEn: 'grinning face', category: 'base', keywords: ['smile', 'happy', '笑脸', '开心'] },
  { id: 'joy', emoji: '😂', name: '笑哭', nameEn: 'face with tears of joy', category: 'base', keywords: ['laugh', 'cry', '笑', '哭'] },
  { id: 'heart-eyes', emoji: '😍', name: '花痴', nameEn: 'smiling face with heart-eyes', category: 'base', keywords: ['love', '爱心', '喜欢'] },
  { id: 'thinking', emoji: '🤔', name: '思考', nameEn: 'thinking face', category: 'base', keywords: ['think', '想', '考虑'] },
  { id: 'thumbs-up', emoji: '👍', name: '点赞', nameEn: 'thumbs up', category: 'base', keywords: ['like', '赞', '好'] },
  { id: 'pray', emoji: '🙏', name: '合十', nameEn: 'folded hands', category: 'base', keywords: ['please', 'thanks', '拜托', '谢谢'] },
  { id: 'blue-heart', emoji: '💙', name: '蓝心', nameEn: 'blue heart', category: 'base', keywords: ['love', '心', '蓝'] },
  { id: 'fire', emoji: '🔥', name: '火', nameEn: 'fire', category: 'base', keywords: ['hot', '热', '火焰'] },
  { id: 'sparkles', emoji: '✨', name: '闪光', nameEn: 'sparkles', category: 'base', keywords: ['star', '闪', '亮'] },
  { id: 'party', emoji: '🎉', name: '庆祝', nameEn: 'party popper', category: 'base', keywords: ['celebrate', '庆祝', '派对'] },
  { id: 'cat', emoji: '🐱', name: '猫脸', nameEn: 'cat face', category: 'base', keywords: ['animal', '猫', '宠物'] },
  { id: 'apple', emoji: '🍎', name: '红苹果', nameEn: 'red apple', category: 'base', keywords: ['fruit', '苹果', '水果'] },
  { id: 'soccer', emoji: '⚽', name: '足球', nameEn: 'soccer ball', category: 'base', keywords: ['ball', '足球', '运动'] },
  { id: 'rocket', emoji: '🚀', name: '火箭', nameEn: 'rocket', category: 'base', keywords: ['ship', '火箭', '发射'] },
  { id: 'rainbow', emoji: '🌈', name: '彩虹', nameEn: 'rainbow', category: 'base', keywords: ['彩虹', '天气'] },
  { id: 'star', emoji: '⭐', name: '星星', nameEn: 'star', category: 'base', keywords: ['星', '收藏'] },
  { id: 'skull', emoji: '💀', name: '骷髅', nameEn: 'skull', category: 'base', keywords: ['dead', '骷髅', '笑死'] },
  { id: 'melting', emoji: '🫠', name: '融化的脸', nameEn: 'melting face', category: 'base', keywords: ['melt', '融化', '尴尬'] },
  { id: 'salute', emoji: '🫡', name: '敬礼的脸', nameEn: 'saluting face', category: 'base', keywords: ['salute', '敬礼', ' respect'] },
  { id: 'heart-hands', emoji: '🫶', name: '比心手势', nameEn: 'heart hands', category: 'base', keywords: ['love', '比心', '心'] },

  // ---- 变体选择符（默认文本呈现 + VS16 请求表情样式）----
  { id: 'airplane-vs16', emoji: '✈️', name: '飞机(表情样式)', nameEn: 'airplane + VS16', category: 'variant', keywords: ['plane', '飞机', '旅行'], baseChar: '✈' },
  { id: 'sun-vs16', emoji: '☀️', name: '太阳(表情样式)', nameEn: 'sun + VS16', category: 'variant', keywords: ['sun', '太阳', '晴'], baseChar: '☀' },
  { id: 'umbrella-vs16', emoji: '☂️', name: '雨伞(表情样式)', nameEn: 'umbrella + VS16', category: 'variant', keywords: ['rain', '雨伞', '下雨'], baseChar: '☂' },
  { id: 'snowman-vs16', emoji: '☃️', name: '雪人(表情样式)', nameEn: 'snowman + VS16', category: 'variant', keywords: ['snow', '雪人', '冬天'], baseChar: '☃' },
  { id: 'phone-vs16', emoji: '☎️', name: '电话(表情样式)', nameEn: 'telephone + VS16', category: 'variant', keywords: ['phone', '电话', '联系'], baseChar: '☎' },
  { id: 'spade-vs16', emoji: '♠️', name: '黑桃(表情样式)', nameEn: 'spade suit + VS16', category: 'variant', keywords: ['poker', '黑桃', '扑克'], baseChar: '♠' },
  { id: 'heart-suit-vs16', emoji: '♥️', name: '红桃(表情样式)', nameEn: 'heart suit + VS16', category: 'variant', keywords: ['poker', '红桃', '扑克', '心'], baseChar: '♥' },
  { id: 'warning-vs16', emoji: '⚠️', name: '警告(表情样式)', nameEn: 'warning + VS16', category: 'variant', keywords: ['warn', '警告', '注意'], baseChar: '⚠' },
  { id: 'arrow-vs16', emoji: '➡️', name: '右箭头(表情样式)', nameEn: 'right arrow + VS16', category: 'variant', keywords: ['arrow', '箭头', '右'], baseChar: '➡' },
  { id: 'keycap-1', emoji: '1️⃣', name: '键帽数字 1', nameEn: 'keycap digit one', category: 'variant', keywords: ['number', '数字', '键帽', '1'] },
  { id: 'keycap-hash', emoji: '#️⃣', name: '键帽 #', nameEn: 'keycap number sign', category: 'variant', keywords: ['number', '键帽', 'hash', '#'] },
  { id: 'smile-vs15', emoji: '☺︎', name: '笑脸(强制文本样式)', nameEn: 'smiling face + VS15', category: 'variant', keywords: ['text style', '文本样式', '笑脸'], baseChar: '☺' },

  // ---- 肤色修饰符 ----
  { id: 'thumbs-light', emoji: '👍🏻', name: '点赞(浅肤色)', nameEn: 'thumbs up: light skin tone', category: 'skin', keywords: ['like', '赞', '肤色'] },
  { id: 'thumbs-medium', emoji: '👍🏽', name: '点赞(中等肤色)', nameEn: 'thumbs up: medium skin tone', category: 'skin', keywords: ['like', '赞', '肤色'] },
  { id: 'wave-dark', emoji: '👋🏿', name: '挥手(深肤色)', nameEn: 'waving hand: dark skin tone', category: 'skin', keywords: ['hello', '挥手', '肤色'] },
  { id: 'pray-mdark', emoji: '🙏🏾', name: '合十(中深肤色)', nameEn: 'folded hands: medium-dark skin tone', category: 'skin', keywords: ['please', '拜托', '肤色'] },
  { id: 'muscle-mlight', emoji: '💪🏼', name: '肌肉(中浅肤色)', nameEn: 'flexed biceps: medium-light skin tone', category: 'skin', keywords: ['strong', '肌肉', '加油', '肤色'] },
  { id: 'person-mdark', emoji: '🧑🏾', name: '成年人(中深肤色)', nameEn: 'person: medium-dark skin tone', category: 'skin', keywords: ['person', '人', '肤色'] },
  { id: 'walk-medium', emoji: '🚶🏽', name: '行人(中等肤色)', nameEn: 'person walking: medium skin tone', category: 'skin', keywords: ['walk', '走路', '肤色'] },
  { id: 'baby-dark', emoji: '👶🏿', name: '婴儿(深肤色)', nameEn: 'baby: dark skin tone', category: 'skin', keywords: ['baby', '婴儿', '肤色'] },

  // ---- ZWJ 序列 ----
  { id: 'family-mwg', emoji: '👨‍👩‍👧', name: '家庭: 男人女人女孩', nameEn: 'family: man, woman, girl', category: 'zwj', keywords: ['family', '家庭', '家人'] },
  { id: 'family-mmb', emoji: '👨‍👨‍👦', name: '家庭: 男人男人男孩', nameEn: 'family: man, man, boy', category: 'zwj', keywords: ['family', '家庭', '家人'] },
  { id: 'family-new', emoji: '🧑‍🧑‍🧒', name: '家庭: 大人大人小孩(新版)', nameEn: 'family: adult, adult, child', category: 'zwj', keywords: ['family', '家庭', '新版'] },
  { id: 'woman-dev', emoji: '👩‍💻', name: '女程序员', nameEn: 'woman technologist', category: 'zwj', keywords: ['coder', '程序员', '工程师', '开发'] },
  { id: 'person-astronaut', emoji: '🧑‍🚀', name: '宇航员', nameEn: 'astronaut', category: 'zwj', keywords: ['space', '宇航员', '太空'] },
  { id: 'couple-heart', emoji: '👩‍❤️‍👨', name: '情侣: 女人男人', nameEn: 'couple with heart: woman, man', category: 'zwj', keywords: ['love', '情侣', '爱心'] },
  { id: 'people-holding', emoji: '🧑‍🤝‍🧑', name: '手拉手的两个人', nameEn: 'people holding hands', category: 'zwj', keywords: ['friends', '手拉手', '朋友'] },
  { id: 'black-cat', emoji: '🐈‍⬛', name: '黑猫', nameEn: 'black cat', category: 'zwj', keywords: ['animal', '黑猫', '宠物'] },
  { id: 'rainbow-flag', emoji: '🏳️‍🌈', name: '彩虹旗', nameEn: 'rainbow flag', category: 'zwj', keywords: ['pride', '彩虹', '旗'] },
  { id: 'pirate-flag', emoji: '🏴‍☠️', name: '海盗旗', nameEn: 'pirate flag', category: 'zwj', keywords: ['pirate', '海盗', '旗'] },
  { id: 'heart-fire', emoji: '❤️‍🔥', name: '燃烧的心', nameEn: 'heart on fire', category: 'zwj', keywords: ['love', '火', '热情'] },
  { id: 'face-clouds', emoji: '😶‍🌫️', name: '云雾中的脸', nameEn: 'face in clouds', category: 'zwj', keywords: ['fog', '迷茫', '云'] },
  { id: 'red-hair', emoji: '🧑‍🦰', name: '红发的人', nameEn: 'person: red hair', category: 'zwj', keywords: ['hair', '红发', '人'] },

  // ---- 旗帜序列 ----
  { id: 'flag-cn', emoji: '🇨🇳', name: '旗帜: 中国', nameEn: 'flag: China', category: 'flag', keywords: ['china', '中国', '国旗', 'cn'] },
  { id: 'flag-us', emoji: '🇺🇸', name: '旗帜: 美国', nameEn: 'flag: United States', category: 'flag', keywords: ['usa', '美国', '国旗', 'us'] },
  { id: 'flag-jp', emoji: '🇯🇵', name: '旗帜: 日本', nameEn: 'flag: Japan', category: 'flag', keywords: ['japan', '日本', '国旗', 'jp'] },
  { id: 'flag-gb', emoji: '🇬🇧', name: '旗帜: 英国', nameEn: 'flag: United Kingdom', category: 'flag', keywords: ['uk', '英国', '国旗', 'gb'] },
  { id: 'flag-fr', emoji: '🇫🇷', name: '旗帜: 法国', nameEn: 'flag: France', category: 'flag', keywords: ['france', '法国', '国旗', 'fr'] },
  { id: 'flag-de', emoji: '🇩🇪', name: '旗帜: 德国', nameEn: 'flag: Germany', category: 'flag', keywords: ['germany', '德国', '国旗', 'de'] },
  { id: 'flag-br', emoji: '🇧🇷', name: '旗帜: 巴西', nameEn: 'flag: Brazil', category: 'flag', keywords: ['brazil', '巴西', '国旗', 'br'] },
  { id: 'flag-in', emoji: '🇮🇳', name: '旗帜: 印度', nameEn: 'flag: India', category: 'flag', keywords: ['india', '印度', '国旗', 'in'] },
  { id: 'flag-kr', emoji: '🇰🇷', name: '旗帜: 韩国', nameEn: 'flag: South Korea', category: 'flag', keywords: ['korea', '韩国', '国旗', 'kr'] },
  { id: 'flag-un', emoji: '🇺🇳', name: '旗帜: 联合国', nameEn: 'flag: United Nations', category: 'flag', keywords: ['un', '联合国', '旗'] },
  { id: 'flag-england', emoji: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', name: '旗帜: 英格兰(标签序列)', nameEn: 'flag: England (tag sequence)', category: 'flag', keywords: ['england', '英格兰', '旗', '细分'] },
  { id: 'flag-white', emoji: '🏳️', name: '白旗', nameEn: 'white flag', category: 'flag', keywords: ['surrender', '白旗', '投降'] },
  { id: 'flag-chequered', emoji: '🏁', name: '终点旗', nameEn: 'chequered flag', category: 'flag', keywords: ['race', '终点', '赛车'] },
];
